 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/time_periods", type: :request do
  # TimePeriod. As you add validations to TimePeriod, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TimePeriod.create! valid_attributes
      get time_periods_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      time_period = TimePeriod.create! valid_attributes
      get time_period_url(time_period)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_time_period_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      time_period = TimePeriod.create! valid_attributes
      get edit_time_period_url(time_period)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TimePeriod" do
        expect {
          post time_periods_url, params: { time_period: valid_attributes }
        }.to change(TimePeriod, :count).by(1)
      end

      it "redirects to the created time_period" do
        post time_periods_url, params: { time_period: valid_attributes }
        expect(response).to redirect_to(time_period_url(TimePeriod.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TimePeriod" do
        expect {
          post time_periods_url, params: { time_period: invalid_attributes }
        }.to change(TimePeriod, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post time_periods_url, params: { time_period: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested time_period" do
        time_period = TimePeriod.create! valid_attributes
        patch time_period_url(time_period), params: { time_period: new_attributes }
        time_period.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the time_period" do
        time_period = TimePeriod.create! valid_attributes
        patch time_period_url(time_period), params: { time_period: new_attributes }
        time_period.reload
        expect(response).to redirect_to(time_period_url(time_period))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        time_period = TimePeriod.create! valid_attributes
        patch time_period_url(time_period), params: { time_period: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested time_period" do
      time_period = TimePeriod.create! valid_attributes
      expect {
        delete time_period_url(time_period)
      }.to change(TimePeriod, :count).by(-1)
    end

    it "redirects to the time_periods list" do
      time_period = TimePeriod.create! valid_attributes
      delete time_period_url(time_period)
      expect(response).to redirect_to(time_periods_url)
    end
  end
end
